# Generated by Django 3.2.5 on 2021-07-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000)),
                ('content', models.TextField(max_length=2000)),
                ('duration', models.IntegerField(default=0)),
                ('type_access', models.CharField(choices=[('life access', 'life access'), ('One year', 'One year')], max_length=20)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.article')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercise')),
            ],
        ),
    ]
